const PAGE_KEYS = {

  USERS: "users",
  SESSIONS: "sessions",
  ACCOUNTS: "accounts",
  ANALYTICS: "analytics",
  DASHBOARD: "dashboard"

};

const USER_STATUS = {

  ACTIVE: "ACTIVE",
  BLOCKED: "BLOCKED"

};

const ACCOUNT_STATUS = {

  AVAILABLE: "AVAILABLE",
  ASSIGNING: "ASSIGNING",
  CLEANING: "CLEANING",
  FAILED: "FAILED"

};

const AWS_SERVICES = [
  { name: "AWS Amplify", icon: "Amplify" },
  { name: "Amazon API Gateway", icon: "API-Gateway" },
  { name: "AWS App Mesh", icon: "App-Mesh" },
  { name: "AWS App Runner", icon: "App-Runner" },
  { name: "AWS AppConfig", icon: "AppConfig" },
  { name: "Amazon AppFlow", icon: "AppFlow" },
  { name: "AWS Application Auto Scaling", icon: "Application-Auto-Scaling" },
  { name: "AWS Application Composer", icon: "Application-Composer" },
  { name: "AWS Application Cost Profiler", icon: "Application-Cost-Profiler" },
  { name: "AWS Application Discovery Service", icon: "Application-Discovery-Service" },
  { name: "AWS Application Migration Service", icon: "Application-Migration-Service" },
  { name: "Amazon AppStream 2.0", icon: "AppStream" },
  { name: "AWS AppSync", icon: "AppSync" },
  { name: "AWS Artifact", icon: "Artifact" },
  { name: "Amazon Athena", icon: "Athena" },
  { name: "AWS Audit Manager", icon: "Audit-Manager" },
  { name: "Amazon A2I", icon: "Augmented-AI-A2I" },
  { name: "Amazon Aurora", icon: "Aurora" },
  { name: "AWS Auto Scaling", icon: "Auto-Scaling" },
  { name: "AWS CLI", icon: "AWS CLI" },
  { name: "AWS Backup", icon: "Backup" },
  { name: "AWS Batch", icon: "Batch" },
  { name: "AWS Billing Conductor", icon: "Billing-Conductor" },
  { name: "AWS Budgets", icon: "Budgets" },
  { name: "AWS Certificate Manager (ACM)", icon: "Certificate-Manager" },
  { name: "AWS Clean Rooms", icon: "Clean-Rooms" },
  { name: "AWS Client VPN", icon: "Client-VPN" },
  { name: "AWS Cloud Control API", icon: "Cloud-Control-API" },
  { name: "Amazon Cloud Directory", icon: "Cloud-Directory" },
  { name: "AWS Cloud Map", icon: "Cloud-Map" },
  { name: "AWS Cloud WAN", icon: "Cloud-WAN" },
  { name: "AWS Cloud9", icon: "Cloud9" },
  { name: "AWS CloudFormation", icon: "CloudFormation" },
  { name: "Amazon CloudFront", icon: "CloudFront" },
  { name: "AWS CloudHSM", icon: "CloudHSM" },
  { name: "Amazon CloudSearch", icon: "CloudSearch" },
  { name: "AWS CloudShell", icon: "CloudShell" },
  { name: "AWS CloudTrail", icon: "CloudTrail" },
  { name: "Amazon CloudWatch", icon: "CloudWatch" },
  { name: "AWS CodeArtifact", icon: "CodeArtifact" },
  { name: "AWS CodeBuild", icon: "CodeBuild" },
  { name: "Amazon CodeCatalyst", icon: "CodeCatalyst" },
  { name: "AWS CodeCommit", icon: "CodeCommit" },
  { name: "AWS CodeDeploy", icon: "CodeDeploy" },
  { name: "Amazon CodeGuru", icon: "CodeGuru" },
  { name: "AWS CodePipeline", icon: "CodePipeline" },
  { name: "AWS CodeStar", icon: "CodeStar" },
  { name: "Amazon CodeWhisperer", icon: "CodeWhisperer" },
  { name: "Amazon Cognito", icon: "Cognito" },
  { name: "Amazon Comprehend Medical", icon: "Comprehend-Medical" },
  { name: "Amazon Comprehend", icon: "Comprehend" },
  { name: "AWS Compute Optimizer", icon: "Compute-Optimizer" },
  { name: "AWS Config", icon: "Config" },
  { name: "Amazon Connect", icon: "Connect" },
  { name: "AWS Control Tower", icon: "Control-Tower" },
  { name: "AWS Cost and Usage Report", icon: "Cost-and-Usage-Report" },
  { name: "AWS Cost Explorer", icon: "Cost-Explorer" },
  { name: "AWS Data Exchange", icon: "Data-Exchange" },
  { name: "AWS Data Pipeline", icon: "Data-Pipeline" },
  { name: "AWS Database Migration Service (DMS)", icon: "Database-Migration-Service" },
  { name: "AWS DataSync", icon: "DataSync" },
  { name: "Amazon DataZone", icon: "DataZone" },
  { name: "Amazon Detective", icon: "Detective" },
  { name: "AWS Device Farm", icon: "Device-Farm" },
  { name: "Amazon DevOps Guru", icon: "DevOps-Guru" },
  { name: "AWS Direct Connect", icon: "Direct-Connect" },
  { name: "AWS Directory Service", icon: "Directory-Service" },
  { name: "AWS Distro for OpenTelemetry", icon: "Distro-for-OpenTelemetry" },
  { name: "Amazon DocumentDB", icon: "DocumentDB" },
  { name: "Amazon DynamoDB", icon: "DynamoDB" },
  { name: "Amazon EC2 Auto Scaling", icon: "EC2-Auto-Scaling" },
  { name: "Amazon EC2 Image Builder", icon: "EC2-Image-Builder" },
  { name: "Amazon EC2", icon: "EC2" },
  { name: "Amazon ECS Anywhere", icon: "ECS-Anywhere" },
  { name: "Amazon EFS", icon: "EFS" },
  { name: "Amazon EKS Anywhere", icon: "EKS-Anywhere" },
  { name: "Amazon EKS Cloud", icon: "EKS-Cloud" },
  { name: "Amazon EKS Distro", icon: "EKS-Distro" },
  { name: "AWS Elastic Beanstalk", icon: "Elastic-Beanstalk" },
  { name: "Amazon EBS", icon: "Elastic-Block-Store" },
  { name: "Amazon ECR", icon: "Elastic-Container-Registry" },
  { name: "Amazon ECS", icon: "Elastic-Container-Service" },
  { name: "Elastic Fabric Adapter (EFA)", icon: "Elastic-Fabric-Adapter" },
  { name: "Amazon Elastic Inference", icon: "Elastic-Inference" },
  { name: "Amazon EKS", icon: "Elastic-Kubernetes-Service" },
  { name: "Elastic Load Balancing", icon: "Elastic-Load-Balancing" },
  { name: "Amazon Elastic Transcoder", icon: "Elastic-Transcoder" },
  { name: "Amazon ElastiCache", icon: "ElastiCache" },
  { name: "Amazon EMR", icon: "EMR" },
  { name: "Amazon EventBridge", icon: "EventBridge" },
  { name: "AWS Express Workflows", icon: "Express-Workflows" },
  { name: "AWS Fargate", icon: "Fargate" },
  { name: "AWS Fault Injection Simulator (FIS)", icon: "Fault-Injection-Simulator" },
  { name: "Amazon FinSpace", icon: "FinSpace" },
  { name: "AWS Firewall Manager", icon: "Firewall-Manager" },
  { name: "Amazon Forecast", icon: "Forecast" },
  { name: "Amazon Fraud Detector", icon: "Fraud-Detector" },
  { name: "Amazon GameLift", icon: "GameLift" },
  { name: "AWS Global Accelerator", icon: "Global-Accelerator" },
  { name: "AWS Glue DataBrew", icon: "Glue-DataBrew" },
  { name: "AWS Glue Elastic Views", icon: "Glue-Elastic-Views" },
  { name: "AWS Glue", icon: "Glue" },
  { name: "AWS Ground Station", icon: "Ground-Station" },
  { name: "Amazon GuardDuty", icon: "GuardDuty" },
  { name: "Amazon HealthLake", icon: "HealthLake" },
  { name: "AWS IAM Identity Center", icon: "IAM-Identity-Center" },
  { name: "AWS IAM", icon: "Identity-and-Access-Management" },
  { name: "Amazon Inspector", icon: "Inspector" },
  { name: "Amazon Interactive Video Service (IVS)", icon: "Interactive-Video-Service" },
  { name: "AWS IoT Analytics", icon: "IoT-Analytics" },
  { name: "AWS IoT Core", icon: "IoT-Core" },
  { name: "AWS IoT Device Defender", icon: "IoT-Device-Defender" },
  { name: "AWS IoT Device Management", icon: "IoT-Device-Management" },
  { name: "AWS IoT Events", icon: "IoT-Events" },
  { name: "AWS IoT ExpressLink", icon: "IoT-ExpressLink" },
  { name: "AWS IoT FleetWise", icon: "IoT-FleetWise" },
  { name: "AWS IoT Greengrass", icon: "IoT-Greengrass" },
  { name: "AWS IoT RoboRunner", icon: "IoT-RoboRunner" },
  { name: "AWS IoT SiteWise", icon: "IoT-SiteWise" },
  { name: "AWS IoT Things Graph", icon: "IoT-Things-Graph" },
  { name: "AWS IoT TwinMaker", icon: "IoT-TwinMaker" },
  { name: "Amazon Kendra", icon: "Kendra" },
  { name: "AWS KMS", icon: "Key-Management-Service" },
  { name: "Amazon Keyspaces", icon: "Keyspaces" },
  { name: "Amazon Kinesis Data Analytics", icon: "Kinesis-Data-Analytics" },
  { name: "Amazon Kinesis Data Streams", icon: "Kinesis-Data-Streams" },
  { name: "Amazon Kinesis Data Firehose", icon: "Kinesis-Firehose" },
  { name: "Amazon Kinesis Video Streams", icon: "Kinesis-Video-Streams" },
  { name: "Amazon Kinesis", icon: "Kinesis" },
  { name: "AWS Lake Formation", icon: "Lake-Formation" },
  { name: "AWS Lambda", icon: "Lambda" },
  { name: "AWS Launch Wizard", icon: "Launch-Wizard" },
  { name: "Amazon Lex", icon: "Lex" },
  { name: "AWS License Manager", icon: "License-Manager" },
  { name: "Amazon Lightsail", icon: "Lightsail" },
  { name: "AWS Local Zones", icon: "Local-Zones" },
  { name: "Amazon Location Service", icon: "Location-Service" },
  { name: "Amazon Lookout for Equipment", icon: "Lookout-for-Equipment" },
  { name: "Amazon Lookout for Metrics", icon: "Lookout-for-Metrics" },
  { name: "Amazon Lookout for Vision", icon: "Lookout-for-Vision" },
  { name: "Amazon Macie", icon: "Macie" },
  { name: "AWS Mainframe Modernization", icon: "Mainframe-Modernization" },
  { name: "Amazon Managed Blockchain", icon: "Managed-Blockchain" },
  { name: "Amazon Managed Grafana", icon: "Managed-Grafana" },
  { name: "Amazon Managed Service for Prometheus", icon: "Managed-Service-for-Prometheus" },
  { name: "Amazon MSK", icon: "Managed-Streaming-for-Apache-Kafka" },
  { name: "Amazon MWAA", icon: "Managed-Workflows-for-Apache-Airflow" },
  { name: "Amazon MemoryDB", icon: "MemoryDB-for-Redis" },
  { name: "AWS Migration Evaluator", icon: "Migration-Evaluator" },
  { name: "AWS Migration Hub", icon: "Migration-Hub" },
  { name: "Amazon Monitron", icon: "Monitron" },
  { name: "Amazon MQ", icon: "MQ" },
  { name: "Amazon Neptune", icon: "Neptune" },
  { name: "AWS Network Firewall", icon: "Network-Firewall" },
  { name: "NICE DCV", icon: "NICE-DCV" },
  { name: "Amazon Nimble Studio", icon: "Nimble-Studio" },
  { name: "AWS Nitro Enclaves", icon: "Nitro-Enclaves" },
  { name: "Amazon Omics", icon: "Omics" },
  { name: "Amazon OpenSearch Service", icon: "OpenSearch-Service" },
  { name: "AWS OpsWorks", icon: "OpsWorks" },
  { name: "AWS Organizations", icon: "Organizations" },
  { name: "AWS Outposts", icon: "Outposts-family" },
  { name: "AWS Outposts rack", icon: "Outposts-rack" },
  { name: "AWS Outposts servers", icon: "Outposts-servers" },
  { name: "AWS Panorama", icon: "Panorama" },
  { name: "AWS ParallelCluster", icon: "ParallelCluster" },
  { name: "Amazon Personalize", icon: "Personalize" },
  { name: "Amazon Pinpoint APIs", icon: "Pinpoint-APIs" },
  { name: "Amazon Pinpoint", icon: "Pinpoint" },
  { name: "Amazon Polly", icon: "Polly" },
  { name: "AWS Private 5G", icon: "Private-5G" },
  { name: "AWS Private CA", icon: "Private-Certificate-Authority" },
  { name: "AWS PrivateLink", icon: "PrivateLink" },
  { name: "AWS Proton", icon: "Proton" },
  { name: "Amazon QLDB", icon: "Quantum-Ledger-Database" },
  { name: "Amazon QuickSight", icon: "QuickSight" },
  { name: "Amazon RDS on VMware", icon: "RDS-on-VMware" },
  { name: "Amazon RDS", icon: "RDS" },
  { name: "Amazon Redshift", icon: "Redshift" },
  { name: "Amazon Rekognition", icon: "Rekognition" },
  { name: "AWS Resilience Hub", icon: "Resilience-Hub" },
  { name: "AWS Resource Access Manager (RAM)", icon: "Resource-Access-Manager" },
  { name: "AWS Resource Explorer", icon: "Resource-Explorer" },
  { name: "AWS RoboMaker", icon: "RoboMaker" },
  { name: "Amazon Route 53", icon: "Route-53" },
  { name: "Amazon SageMaker Ground Truth", icon: "SageMaker-Ground-Truth" },
  { name: "Amazon SageMaker Studio Lab", icon: "SageMaker-Studio-Lab" },
  { name: "Amazon SageMaker", icon: "SageMaker" },
  { name: "AWS Secrets Manager", icon: "Secrets-Manager" },
  { name: "AWS Security Hub", icon: "Security-Hub" },
  { name: "Amazon Security Lake", icon: "Security-Lake" },
  { name: "AWS Server Migration Service (SMS)", icon: "Server-Migration-Service" },
  { name: "AWS Serverless Application Repository", icon: "Serverless-Application-Repository" },
  { name: "AWS Service Catalog", icon: "Service-Catalog" },
  { name: "AWS Shield", icon: "Shield" },
  { name: "AWS Signer", icon: "Signer" },
  { name: "Amazon SES", icon: "Simple-Email-Service" },
  { name: "Amazon SNS", icon: "Simple-Notification-Service" },
  { name: "Amazon SQS", icon: "Simple-Queue-Service" },
  { name: "Amazon S3 Glacier", icon: "Simple-Storage-Service-Glacier" },
  { name: "Amazon S3", icon: "Simple-Storage-Service" },
  { name: "AWS SimSpace Weaver", icon: "SimSpace-Weaver" },
  { name: "AWS Site-to-Site VPN", icon: "Site-to-Site-VPN" },
  { name: "AWS Snowball Edge", icon: "Snowball-Edge" },
  { name: "AWS Snowball", icon: "Snowball" },
  { name: "AWS Snowcone", icon: "Snowcone" },
  { name: "AWS Snowmobile", icon: "Snowmobile" },
  { name: "AWS Step Functions", icon: "Step-Functions" },
  { name: "AWS Storage Gateway", icon: "Storage-Gateway" },
  { name: "AWS Supply Chain", icon: "Supply-Chain" },
  { name: "AWS Systems Manager", icon: "Systems-Manager" },
  { name: "Amazon Textract", icon: "Textract" },
  { name: "Amazon Timestream", icon: "Timestream" },
  { name: "Amazon Transcribe", icon: "Transcribe" },
  { name: "AWS Transfer Family", icon: "Transfer-Family" },
  { name: "AWS Transit Gateway", icon: "Transit-Gateway" },
  { name: "Amazon Translate", icon: "Translate" },
  { name: "AWS Trusted Advisor", icon: "Trusted-Advisor" },
  { name: "AWS Verified Access", icon: "Verified-Access" },
  { name: "Amazon Verified Permissions", icon: "Verified-Permissions" },
  { name: "Amazon VPC", icon: "Virtual-Private-Cloud" },
  { name: "Amazon VPC Lattice", icon: "VPC-Lattice" },
  { name: "AWS WAF", icon: "WAF" },
  { name: "AWS Wavelength", icon: "Wavelength" },
  { name: "AWS Well-Architected Tool", icon: "Well-Architected-Tool" },
  { name: "Amazon WorkDocs", icon: "WorkDocs" },
  { name: "Amazon WorkMail", icon: "WorkMail" },
  { name: "Amazon WorkSpaces", icon: "WorkSpaces-Family" },
  { name: "AWS X-Ray", icon: "X-Ray" }
];